[package]
name = "ray-tracer-challenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.bench]
debug = true

[dependencies]
by_address = "1.1.0"

[[bench]]
name = "ray_tracer"
harness = false
